#!/bin/bash
set -o errexit

pip install -r requirements.txt

cat <<EOF > magictale/local_settings.py
# This file is automatically generated by the build.sh script
import os
CELERY_BROKER_URL = os.getenv("REDIS_URL")
CELERY_RESULT_BACKEND = os.getenv("REDIS_URL")
FIREBASE_CREDENTIALS_JSON_STR = os.getenv("FIREBASE_CREDENTIALS_JSON")
EOF

python manage.py collectstatic --no-input
python manage.py migrate