# Generated by Django 5.2.5 on 2025-09-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(default='MagicTales AI', max_length=100)),
                ('application_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('default_language', models.CharField(default='English', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
            ],
        ),
    ]
