# Generated by Django 5.2.5 on 2025-09-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('getting_started', 'Getting Started'), ('subscription', 'Subscription & Billing'), ('parental', 'Parental Controls'), ('technical', 'Technical Issues')], max_length=50)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Order to display items (lower numbers first).')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
