# Generated by Django 5.2.5 on 2025-09-03 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creator_name', models.CharField(default='By MagicTales', max_length=100)),
                ('synopsis', models.TextField()),
                ('cover_image_url', models.URLField(max_length=1024)),
                ('is_premium', models.BooleanField(default=True, help_text='Requires a subscription to access')),
            ],
            options={
                'verbose_name': 'Gallery Story',
                'verbose_name_plural': 'Gallery Stories',
            },
        ),
        migrations.CreateModel(
            name='StoryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('pronouns', models.CharField(max_length=50)),
                ('favorite_animal', models.CharField(max_length=100)),
                ('favorite_color', models.CharField(max_length=50)),
                ('theme', models.CharField(max_length=80)),
                ('art_style', models.CharField(max_length=80)),
                ('language', models.CharField(default='English', max_length=40)),
                ('voice', models.CharField(blank=True, default='', max_length=80)),
                ('length', models.CharField(choices=[('short', 'short'), ('medium', 'medium'), ('long', 'long')], default='short', max_length=20)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('custom_prompt', models.TextField(blank=True, default='')),
                ('synopsis', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=1024)),
                ('is_saved', models.BooleanField(default=False)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('model_used', models.CharField(default='gpt-4o-mini', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('onboarding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='authentication.onboardingstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GenerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ai.storyproject')),
            ],
        ),
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('image_url', models.URLField(blank=True, default='', max_length=1024)),
                ('audio_url', models.URLField(blank=True, default='', max_length=1024)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ai.storyproject')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('project', 'index')},
            },
        ),
    ]
