# Generated by Django 5.2.5 on 2025-10-09 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('audio_url', models.URLField(blank=True, default='', max_length=1024)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ai.storyproject')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('project', 'index')},
            },
        ),
    ]
