# Generated by Django 5.2.5 on 2025-09-03 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryStory',
        ),
    ]
